#!/bin/bash
###### Update /etc/rc.local, note this file must have \r terminated lines and not \r\n ######

cat > /etc/rc.local << "EOF"
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

echo pcf2129 0x51 > /sys/class/i2c-dev/i2c-0/device/new_device
( sleep 2; hwclock -s ) &


/usr/bin/energy_monitor &

exit 0
EOF
